### ISSUE TITLE
Connecting to device results in error 133

### ISSUE THREAD

**Issue by sgserg** [PunchThrough/ble-starter-android#6] opened 2021-07-04 09:05 UTC
Changing one line ConnectionManager.kt:225

`device.connectGatt(context, false, callback)`

to

`device.connectGatt(context, false, callback, BluetoothDevice.TRANSPORT_LE)`

solves the problem (although requires to target SDK at least 23)

**Comment by cheeyi** [comment] 2021-08-16 05:14
@sgserg Sorry for the delayed response. Thanks for reporting this issue! We'll keep this issue open for when we move the library to target a minSdkVersion of 23. For now, we're sticking to 21 and so some OEM devices may not work well. Would you mind also posting your device that failed to connect using `connectGatt`? Device manufacturer, Android version, etc.

**Comment by sgserg** [comment] 2021-08-16 07:17
@cheeyi Sure, tested on Maize M6s, Android version 7.0, Flyme 6.3.1.0G

**Comment by cheeyi** [comment] 2024-04-09 07:34
We have a list of possible reasons that could trigger a `133` error in https://punchthrough.com/android-ble-guide/#Connecting-To-A-BLE-Device. Closing due to inability for our team to reproduce this issue reliably.

**Closed as completed by cheeyi** 2024-04-09 07:34 UTC
Labels: enhancement
